const fs = require('fs');
const path = require('path');

// 1. Find all JavaScript files in the current folder (except this script itself)
const files = fs.readdirSync(__dirname)
    .filter(file => file.endsWith('.js') && file !== 'generateReadme.js');

let tableRows = '';
let count = 1;

// 2. Read each file and extract the Title, Difficulty, and Tags
for (let file of files) {
    const filePath = path.join(__dirname, file);
    const content = fs.readFileSync(filePath, 'utf8');

    // Use regular expressions to find the metadata comments
    const titleMatch = content.match(/\/\/\s*Title:\s*(.*)/i);
    const diffMatch = content.match(/\/\/\s*Difficulty:\s*(.*)/i);
    const tagsMatch = content.match(/\/\/\s*Tags:\s*(.*)/i);

    // Fallback values if you forgot to add comments
    const title = titleMatch ? titleMatch[1].trim() : file.replace('.js', '');
    const difficulty = diffMatch ? diffMatch[1].trim() : 'Unknown';
    const tags = tagsMatch ? tagsMatch[1].trim() : 'None';

    // 3. Build the markdown row
    tableRows += `| ${count} | ${title} | ${difficulty} | [Code](./${file}) | ${tags} |\n`;
    count++;
}

// 4. Create the final README content
const readmeContent = `# 🚀 JavaScript Challenge Tracker

A personal log of my daily coding progress. Updated automatically!

## 📊 Problem Log

| # | Problem Name | Difficulty | Solution Link | Key Concepts / Tags |
|---|--------------|------------|---------------|---------------------|
${tableRows}
*Tip: This table is auto-generated by running \`node generateReadme.js\`*
`;

// 5. Write it to the README.md file
fs.writeFileSync(path.join(__dirname, 'README.md'), readmeContent);
console.log('✅ README.md successfully updated with latest table!');
